// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "test",
            "endpoint": "https://z590atthjh.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://emtmzcqu4nguta4medmxgunsyu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-east-1:b4b63bfb-13eb-47fe-8c02-7f69f618c028",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_u3fRhtLRT",
    "aws_user_pools_web_client_id": "6e7opta5ndlbm5ntup9elibude",
    "aws_content_delivery_bucket": "awsamplifyvue-20181001085456--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://awsamplifyvue-20181001085456--hostingbucket.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
